# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

[[smithy-rs]]
message = "Fix link to Developer Guide in crate's README.md"
references = ["smithy-rs#1262"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "liubin"

[[aws-sdk-rust]]
message = "Fix link to Developer Guide in crate's README.md"
references = ["smithy-rs#1262"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "liubin"

[[smithy-rs]]
message = "Update all runtime crates to [edition 2021](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html)"
references = ["aws-sdk-rust#490"]
meta = { "breaking" = true, "tada" = false, "bug" = false }
author = "Velfi"

[[aws-sdk-rust]]
message = "Update all SDK and runtime crates to [edition 2021](https://blog.rust-lang.org/2021/10/21/Rust-1.56.0.html)"
references = ["aws-sdk-rust#490"]
meta = { "breaking" = true, "tada" = false, "bug" = false }
author = "Velfi"

[[aws-sdk-rust]]
message = "Treat blank environment variable credentials (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`) as missing instead of attempting to use them to sign requests."
references = ["aws-sdk-rust#1271"]
meta = { "breaking" = false, "tada" = false, "bug" = true }
author = "elrob"

[[aws-sdk-rust]]
message = "Add support for configuring the session length in [AssumeRoleProvider](https://docs.rs/aws-config/latest/aws_config/sts/struct.AssumeRoleProvider.html)"
references = ["aws-sdk-rust#479", "smithy-rs#1296"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "rcoh"

[[aws-sdk-rust]]
message = "Add caching to [AssumeRoleProvider](https://docs.rs/aws-config/latest/aws_config/sts/struct.AssumeRoleProvider.html)"
references = ["smithy-rs#1296"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "rcoh"

[[smithy-rs]]
message = "Update urlencoding crate to v2.1.0"
references = ["smithy-rs#1301"]
meta = { "breaking" = false, "tada" = false, "bug" = false }
author = "benesch"

[[smithy-rs]]
message = """
Lossy converters into integer types for `aws_smithy_types::Number` have been
removed. Lossy converters into floating point types for
`aws_smithy_types::Number` have been suffixed with `_lossy`. If you were
directly using the integer lossy converters, we recommend you use the safe
converters.

_Before:_

```rust
fn f1(n: aws_smithy_types::Number) {
    let foo: f32 = n.to_f32(); // Lossy conversion!

    let bar: u32 = n.to_u32(); // Lossy conversion!
}
```

_After:_

```rust
fn f1(n: aws_smithy_types::Number) {
    use std::convert::TryInto; // Unnecessary import if you're using Rust 2021 edition.

    let foo: f32 = n.try_into().expect("lossy conversion detected"); // Or handle the error instead of panicking.

    // You can still do lossy conversions, but only into floating point types.
    let foo: f32 = n.to_f32_lossy();

    // To lossily convert into integer types, use an `as` cast directly.
    let bar: u32 = n as u32; // Lossy conversion!
}
```
"""
references = ["smithy-rs#1274"]
meta = { "breaking" = true, "tada" = false, "bug" = true }
author = "david-perez"
