# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"

# [[aws-sdk-rust]]
# message = "The S3 presigning example was updated to include the metadata field and now includes a curl command generator."
# references = ["aws-sdk-rust#423"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "Velfi"

# [[aws-sdk-rust]]
# message = "Added `impl Into<http::request::Builder> for PresignedRequest`"
# references = ["aws-sdk-rust#423"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "Velfi"
